Repository COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker, pull requests merged in 2020-09, with the labels that each got.

#6 added requirements and added boilerplate
  __pycache__/main.cpython-38.pyc
  main.py
  requriements.txt
Labels: good first issue

#8 updated the README
  README.md
Labels: documentation

#9 Delete readme.md
  readme.md
Labels: documentation

#11 Deckbuilder
  .DS_Store
  __pycache__/utils.cpython-38.pyc
  card_data/set1-en_us.json
  main.py
  requirements.txt
  requriements.txt
  templates/.DS_Store
  templates/deckbuilder.html
  utils.py
Labels: enhancement

#14 Home
  main.py
  templates/Home.html
Labels: enhancement

#13 Deckbuilder
  .gitignore
  decks/.DS_Store
  main.py
  requirements.txt
  templates/deckbuilder.html
  utils.py
Labels: enhancement

#15 fixed champ
  decks/mydeck.csv
  main.py
  templates/deckbuilder.html
  utils.py
Labels: enhancement

#16 Alex/card info prototype
  .DS_Store
  .gitignore
  card_data/set1-en_us.json
  gallery.py
  main.py
  templates/.DS_Store
  templates/gallery/card.html
  templates/gallery/index.html
Labels: enhancement

#20 Adding filter
  utils.py
Labels: enhancement

#21 Kris
  README.md
  decks/newdeck.csv
  use-case-diagram-database.png
Labels: documentation

#22 Alex/card info prototype
  gallery.py
  templates/gallery/card.html
Labels: enhancement
